framework:
    secret: '%env(APP_SECRET)%'

    session:
        enabled: true

    form:
        csrf_protection:
            enabled: true
            field_name: '_token'  # Optionnel, pour personnaliser le nom du champ CSRF
